### ISSUE TITLE
Get - set canvas

### ISSUE THREAD

**Issue by dinami-k** [teynon/ZPL-Label-Designer#2]
How can i get canvas code generated to save in database and after reload? thanks

**Comment by teynon** [comment]
Hi. There is not a way to do so currently. A simple json object export / import would probably not be hard to add. However, I haven't worked on this project in a while, so if you would like to add a feature, I would be likely to accept changes.

**Comment by mayankmrc3** [comment]
I am getting this error. Please help.
ReferenceError: event is not defined[Learn More] designer.js:114:5 
ReferenceError: event is not defined[Learn More] designer.js:268:7 

Thank you
