### ISSUE TITLE
Need help to add some options

### ISSUE THREAD

**Issue by vbnvicky** [teynon/ZPL-Label-Designer#3]
Hi Teynon,

I want to add some options like 2D barcode and borders. Can you help me into this.

Thank you,
Vikrant

**Comment by teynon** [comment]
Hi Vikrant,

   For borders, you could just create a couple of rectangles. However, a quick "border" feature could be added that builds those four rectangles automatically. A 2D Barcode would need a new component in the designer. I don't have access to a printer right now and that was my primary way of ensuring proper output / design views. I also have limited time at the moment. If I find some time and there is enough interest and got my hands on a printer and for development & testing, I may be able to work on that.

**Comment by vbnvicky** [comment]
Hi Teynon,
Thank you for reply.
Can you share your email so that we can communicate over there.

Regards,
Vikrant
