### ISSUE TITLE
Help with setting up the size of the label in the designer.

### ISSUE THREAD

**Issue by andersonseibert** [teynon/ZPL-Label-Designer#4]
I need help to set up the size of the label, i didnt undestand how it works, so i have a label width: 8.8cm and height: 3.5cm how i can i make this in the designer?
I cant understand how de DPI works.
thanks!

**Comment by teynon** [comment]
DPI stands for Dots Per Inch. You have to match the DPI of your printer to the DPI of the label. If the printer is 200 DPI, then your label needs to be designed for 200 DPI. So if you have a printer that prints 200 DPI and you need 8.8cm wide, you need to a label that is 692 dots wide.

The label designer automatically determines the DOT width of the label. You enter the width in inches, however, so if your label is 8.8cm x 3.5cm, then you need to use 3.46457in x 1.37795in.

**Comment by andersonseibert** [comment]
Thanks.
Just another thing, how do you calculate this 8.8cm x 3.5cm to -> 3.46457 x 1.37795

**Comment by teynon** [comment]
https://www.google.com/search?q=cm+to+inches

**Comment by andersonseibert** [comment]
perfect, thanks!
